base_dir: ~/osint-reports

api_keys:
  intelx: ${INTELX}
  shodan: ${SHODAN}
  haveibeenpwned: ${HAVEIBEENPWNED}
  virustotal: ${VIRUSTOTAL}
  mxtoolbox: ${MXTOOLBOX}
  c99: ${C99}
  dnsdumpster: ${DNSDUMPSTER}
  abuseipdb: ${ABUSEIPDB}
  searchengine: $(SEARCHENGINE)
  programmablesearchengine: $(PROGRAMMABLESEARCHENGINE)
  imgbb: $(IMGBB)
  thumbsnap: $(THUMBSNAP)

email_without_domain_regex: "[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+)*@"
haveibeenpwned_request_delay_in_seconds: 1.5

googlehacking:
  max_workers: 20 #total threads to check for dorks
  timeout: 10 #maximum times for each dork request
  dork_file: #optional files used for custom dorks to test
    - ~/dork_file
  exploitdb_categories: #dork retrieved by category from https://www.exploit-db.com/google-hacking-database
    "Sensitive Directories": 
      max_dorks: 5 #process the first n dorks
      authors: #filter based on author, if empty it means every author is valid
